# Create a new conda environment:
#   $ cd pyxel
#   $ conda update -n base conda
#   $ conda deactivate
#   $ conda env create -f continuous_integration/environment.yml
#   $ conda activate pyxel-dev
#   (pyxel_dev) $ pip install --no-deps -e .

# Get a list of all the environments:
#  $ conda env list -v

# Upgrade a conda environment
#  $ conda env update -f environment.yml [-n CONDA_ENV_NAME]
#  $ conda env update [-n CONDA_ENV_NAME] --all

# Remove a conda environment
#  $ conda env remove --name MYENV


name: pyxel-dev
channels:
  - conda-forge
dependencies:
# Python
  - python=3.11
  - pip
# Scientific computing
  - numba>=0.56.4
  - numpy>=1.24
  - pandas>=1.5
  - scipy>=1.10
  - xarray>=2024.10.0
  - photutils
  - poppy>=1.1.0
  - specutils>=1.2
  - synphot
  # Plotting
  - matplotlib-base>=3.6
  - seaborn
  - hvplot
  - bokeh>=3.3.0
# Parallel computing
  - dask>=2.9
  - dask-labextension
# Jupyter notebook
  - ipywidgets>=7.5
  - jupyterlab
  - ipympl              # Interactive Matplotlib in Jupyter
# Input/Output
  - astropy>=5.2
  - astroquery
  - fsspec>=2021
  - aiohttp             # For fsspec
  - h5py
  - pyyaml
  - xlrd
  - openpyxl
  - h5netcdf
  - asdf
  - pooch>=1.1.0
# Others
  - attrs
  - click
  - diskcache
  - tqdm
  - typing-extensions>=4.9
  - pygmo>=2.16.1
  - pympler
  - pillow
  - scikit-image>=0.20.0
  - rich
# Code formatting
  - black>=20
  - isort>=5
  - jupyterlab_code_formatter
# Documentation
  - doc8
  - sphinx
  - sphinx-book-theme
  - sphinxcontrib-bibtex
  - sphinx-panels
  - sphinx-inline-tabs
  - myst-nb
  - sphinx-copybutton
#  - jupyter-book
# Development
  - flake8
  - mypy
  - pre-commit
  - pytest
  - pytest-httpserver
  - pytest-mock
  - tox
  - tryceratops
  - freezegun
  - codespell
# Profiling
  - pyinstrument
#  - memray
# Pip packages
  - pip:
#    - --no-deps
    - lacosmic
